# Site setings
name: 'Hossein'
description: 'Java Developer'
meta_description: 'Hossein Fakhraei Weblog.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there! My name is Hossein Fakhraei. I'm a Java Developer and I am writing my notes here. I hope my notes be useful for everyone"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://hfakhraei.github.io/
disqus:
mailchimp_url:
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: HFakhraei@outlook.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'hfakhraei'
facebook: 'hfakhraei'
github: 'hfakhraei'
codepen: 
dribbble: 
medium: 
instagram: 'hfakhraei'
pinterest: 
linkedin: 'hfakhraei'
producthunt: 
quora: 

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
